version: "3"
services:
  nextjs-focus-app:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3003:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=<your-db-host>
      - DB_USER=<your-db-user>
      - DB_PASSWORD=<your-db-password>
      - DB_NAME=<your-db-name>
      - NEXTAUTH_URL=http://localhost:3003
      - NEXTAUTH_SECRET=<your-nextauth-secret>
